first_name_locator = '#firstname'
last_name_locator = '#lastname'
email_locator = '#email_address'
password_locator = '#password'
confirm_password_locator = '#password-confirmation'
create_account_button_locator = '//*[@class="action submit primary"]'
email_success_locator = '[class="box-content"] > p > br'
message_success_locator = '//*[@data-ui-id="message-success"]'
already_created_message_locator = '//*[@data-ui-id="message-error"]'
account_dropdown_locator = '//*[@class="action switch"]'
logout_button_locator = 'li[class="authorization-link"] > a'
first_name_required_locator = '#firstname-error'
last_name_required_locator = '#lastname-error'
email_required_locator = '#email_address-error'
password_required_locator = '#password-error'
confirm_password_required_locator = '#password-confirmation-error'
